using diamond_kata;

Console.WriteLine("Diamond shape generated by passing letter 'A':");
Console.WriteLine(DiamondKata.GenerateDiamond('A'));
Console.WriteLine();

Console.WriteLine("Diamond shape generated by passing letter 'B':");
Console.WriteLine(DiamondKata.GenerateDiamond('B'));
Console.WriteLine();

Console.WriteLine("Diamond shape generated by passing letter 'C':");
Console.WriteLine(DiamondKata.GenerateDiamond('C'));
Console.WriteLine();

Console.WriteLine("Diamond shape generated by passing letter 'D':");
Console.WriteLine(DiamondKata.GenerateDiamond('D'));
Console.WriteLine();
